AWSTemplateFormatVersion: 2010-09-09
Description: The stack for Snipper, code snippet manager

# Parameters:
#   ApiLogRetentionDays:
#     Type: Number
#     Description: The number of days to keep CloudWatch logs for the APIs
#     Default: 14

Resources:
  CategoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: Slug
          AttributeType: S
      KeySchema:
        - AttributeName: Slug
          KeyType: HASH
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W74
            reason: Encryption is not needed

  SnippetFileTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: Category
          AttributeType: S
        - AttributeName: Id
          AttributeType: S
        - AttributeName: Name
          AttributeType: S
        - AttributeName: FileName
          AttributeType: S
        - AttributeName: Content
          AttributeType: S
      KeySchema:
        - AttributeName: Category
          KeyType: HASH
        - AttributeName: Id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: SnippetCategory
          KeySchema:
            - AttributeName: Category
              KeyType: HASH
            - AttributeName: Id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: SnippetSearch
          KeySchema:
            - AttributeName: Content
              KeyType: HASH
            - AttributeName: Id
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - Category
              - FileName
              - Language
              - SnippetId
              - Name
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W74
            reason: Encryption is not needed


Outputs:
  CategoryTableName:
    Description: The name of the category table
    Value: !Ref CategoryTable
  SnippetFileTableName:
    Description: The name of the snippet file table
    Value: !Ref SnippetFileTable
